/******************************************************
Generated by Postgres.tt
******************************************************/

CREATE TABLE Domains (
Id                        SMALLSERIAL     NOT NULL,
Name                      VARCHAR(50)     NOT NULL,
CONSTRAINT PK_Zones PRIMARY KEY (Id)
);

CREATE TABLE ARecords (
DomainId                  SMALLINT        NOT NULL,
Name                      VARCHAR(50)     NOT NULL,
IpAddress                 VARCHAR(15)     NULL,
DynamicFQDN               VARCHAR(255)    NULL,
CONSTRAINT PK_SubDomains PRIMARY KEY (DomainId,Name),
CONSTRAINT FK_ARecords_Domains FOREIGN KEY (DomainId) REFERENCES Domains(Id)
);

CREATE TABLE MxRecords (
DomainId                  SMALLINT        NOT NULL,
Name                      VARCHAR(50)     NOT NULL,
Priority                  SMALLINT        NOT NULL,
CONSTRAINT PK_MxRecords PRIMARY KEY (DomainId,Name),
CONSTRAINT FK_MxRecords_Domains FOREIGN KEY (DomainId) REFERENCES Domains(Id)
);

CREATE TABLE NsRecords (
DomainId                  SMALLINT        NOT NULL,
Name                      VARCHAR(50)     NOT NULL,
SortOrder                 SMALLINT        NOT NULL,
CONSTRAINT PK_NsRecords PRIMARY KEY (DomainId,Name),
CONSTRAINT FK_NsRecords_Domains FOREIGN KEY (DomainId) REFERENCES Domains(Id)
);

CREATE TABLE CNameRecords (
DomainId                  SMALLINT        NOT NULL,
Name                      VARCHAR(50)     NOT NULL,
CanonicalName             VARCHAR(255)    NULL,
CONSTRAINT PK_CNameRecords PRIMARY KEY (DomainId,Name),
CONSTRAINT FK_CNameRecords_Domains FOREIGN KEY (DomainId) REFERENCES Domains(Id)
);